sdd-postgres:
  build: docker-images/postgres
  ports:
    - "5432:5432"
  volumes_from:
    - sdd-data
  env_file: .env

sdd-data:
  build: docker-images/data
  volumes:
    - /data

sdd-datalake:
  build: docker-images/datalake
  volumes:
    - /datalake

sdd-jupyter:
  build: docker-images/jupyter
  hostname: sdd-jupyter
  #command: python /home/jovyan/work/sdd-ingesta.py

  links:
    - sdd-postgres

  ports:
    - 8888:8888

  volumes_from:
    - sdd-data
